# Pipeline for running GitHub Copilot PR Reviewer Agent
# This pipeline installs the Copilot CLI and invokes the PR reviewer agent
# to conduct automated code reviews on pull requests.
trigger: none
pr: none

parameters:
  - name: PRNumber
    displayName: 'Pull Request Number'
    type: string
    default: '20537'
  - name: pool
    type: object
    default:
      name: Azure Pipelines
      vmImage: macOS-15

variables:
  - template: /eng/pipelines/common/variables.yml@self
  - name: Codeql.Enabled
    value: false

stages:
  - stage: ReviewPR
    displayName: 'Run PR Reviewer Agent'
    jobs:
      - job: CopilotReview
        displayName: 'Run Copilot PR Reviewer Agent'
        pool: ${{ parameters.pool }}
        timeoutInMinutes: 180
        steps:
          - checkout: self
            fetchDepth: 0
            persistCredentials: true

          - script: echo "Testing PR Number ${{ parameters.PRNumber }}"
            displayName: 'Show Parameters'

          # Provision environment
          - template: common/provision.yml
            parameters:
              skipXcode: false
              skipProvisionator: false
              skipAndroidCommonSdks: true
              skipAndroidPlatformApis: true
              skipJdk: true
              skipSimulatorSetup: false
              skipCertificates: true
              skipAndroidEmulatorImages: true
              skipAndroidCreateAvds: true

          # Install .NET and workloads
          - pwsh: ./build.ps1 --target=dotnet --configuration="Release" --verbosity=diagnostic
            displayName: 'Install .NET and workloads'
            retryCountOnTaskFailure: 2
            env:
              DOTNET_TOKEN: $(dotnetbuilds-internal-container-read-token)
              PRIVATE_BUILD: $(PrivateBuild)

          - pwsh: echo "##vso[task.prependpath]$(DotNet.Dir)"
            displayName: 'Add .NET to PATH'

          # Build MSBuild tasks
          - pwsh: ./build.ps1 --target=dotnet-buildtasks --configuration="Release" --verbosity=diagnostic
            displayName: 'Build MSBuild Tasks'
            retryCountOnTaskFailure: 2

          # Boot iOS Simulator
          - script: |
              echo "=== Booting iOS Simulator ==="
              
              # Find and boot a suitable simulator
              UDID=$(xcrun simctl list devices available --json | jq -r '
                .devices | to_entries | 
                map(select(.key | test("iOS"))) | 
                sort_by(.key) | reverse | 
                .[0].value | 
                map(select(.name | test("iPhone (Xs|14|15)"))) | 
                .[0].udid // empty
              ')
              
              if [ -z "$UDID" ]; then
                echo "No preferred simulator found, using first available iPhone"
                UDID=$(xcrun simctl list devices available --json | jq -r '
                  .devices | to_entries | 
                  map(.value) | flatten | 
                  map(select(.name | test("iPhone"))) | 
                  .[0].udid
                ')
              fi
              
              echo "Booting simulator: $UDID"
              xcrun simctl boot "$UDID" 2>/dev/null || echo "Simulator may already be booted"
              sleep 10
              
              echo "Booted simulators:"
              xcrun simctl list devices booted
              
              echo "##vso[task.setvariable variable=IOS_SIMULATOR_UDID]$UDID"
            displayName: 'Boot iOS Simulator'
            timeoutInMinutes: 5

          # Install Node.js
          - script: |
              echo "Installing Node.js..."
              brew install node@22 || brew link --overwrite node@22
              node --version
              npm --version
            displayName: 'Install Node.js'

          # Install Appium
          - script: |
              echo "Installing Appium..."
              NPM_BIN=$(npm config get prefix)/bin
              export PATH="$NPM_BIN:$PATH"
              npm install -g appium
              appium driver install xcuitest
              echo "##vso[task.prependpath]$NPM_BIN"
              echo "Appium version: $(appium --version)"
              appium driver list --installed
            displayName: 'Install Appium'

          # Install GitHub Copilot CLI
          - script: |
              echo "Installing GitHub Copilot CLI..."
              NPM_BIN=$(npm config get prefix)/bin
              export PATH="$NPM_BIN:$PATH"
              npm install -g @github/copilot
              if ! which copilot; then
                echo "##vso[task.logissue type=error]Failed to install GitHub Copilot CLI"
                exit 1
              fi
              echo "Copilot CLI installed: $(copilot --version)"
              
              # Capture DEVELOPER_DIR for subsequent steps
              XCODE_DEV_DIR=$(xcrun xcode-select -p)
              echo "Setting XCODE_DEV_DIR for pipeline: $XCODE_DEV_DIR"
              echo "##vso[task.setvariable variable=XCODE_DEV_DIR]$XCODE_DEV_DIR"
            displayName: 'Install GitHub Copilot CLI'

          # Run PR Reviewer Agent via Review-PR.ps1
          - pwsh: |
              Write-Host "=== Running PR Reviewer Agent ==="
              Write-Host "PR Number: ${{ parameters.PRNumber }}"
              Write-Host "Platform: ios"
              Write-Host "DEVELOPER_DIR: $env:DEVELOPER_DIR"
              
              # Create output directory
              New-Item -ItemType Directory -Force -Path "$(Build.ArtifactStagingDirectory)/copilot-logs" | Out-Null
              
              # Run Review-PR.ps1 in non-interactive mode (default behavior, no flag needed)
              # -SkipMerge because we're already on the branch with PR changes
              & "./.github/scripts/Review-PR.ps1" `
                -PRNumber "${{ parameters.PRNumber }}" `
                -Platform ios `
                -SkipMerge 2>&1 | Tee-Object -FilePath "$(Build.ArtifactStagingDirectory)/copilot-logs/copilot_review_output.md"
              
              $exitCode = $LASTEXITCODE
              Write-Host "Review-PR.ps1 exit code: $exitCode"
              
              # Copy any Copilot session files
              if (Test-Path "$HOME/.copilot") {
                Write-Host "Copying Copilot session state..."
                Copy-Item -Path "$HOME/.copilot" -Destination "$(Build.ArtifactStagingDirectory)/copilot-logs/copilot-session-state" -Recurse -Force -ErrorAction SilentlyContinue
              }
              
              # Copy CustomAgentLogsTmp if it exists
              if (Test-Path "CustomAgentLogsTmp") {
                Write-Host "Copying CustomAgentLogsTmp..."
                Copy-Item -Path "CustomAgentLogsTmp" -Destination "$(Build.ArtifactStagingDirectory)/copilot-logs/" -Recurse -Force -ErrorAction SilentlyContinue
              }
              
              exit $exitCode
            displayName: 'Run PR Reviewer Agent'
            timeoutInMinutes: 150
            env:
              GITHUB_TOKEN: $(COPILOT_TOKEN)
              DEVICE_UDID: $(IOS_SIMULATOR_UDID)
              # Ensure Copilot CLI and its sub-agents use the correct Xcode version
              DEVELOPER_DIR: $(XCODE_DEV_DIR)

          # Publish Copilot logs
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Copilot Logs'
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/copilot-logs'
              artifact: 'CopilotLogs'
            condition: succeededOrFailed()
