# Simplified pipeline for testing UI Tests on iOS Simulator
trigger: none
pr: none

parameters:
  - name: PRNumber
    displayName: 'Pull Request Number'
    type: string
    default: '20537'
  - name: pool
    type: object
    default:
      name: Azure Pipelines
      vmImage: macOS-15

variables:
  - template: /eng/pipelines/common/variables.yml@self
  - name: Codeql.Enabled
    value: false

stages:
  - stage: GatePhase
    displayName: 'Gate - UI Tests on Simulator'
    jobs:
      - job: RunUITests
        displayName: 'Build and Run UI Tests'
        pool: ${{ parameters.pool }}
        timeoutInMinutes: 90
        steps:
          - checkout: self
            fetchDepth: 0

          - script: echo "PR Number:${{ parameters.PRNumber }}"
            displayName: 'Show Parameters'

          # Provision environment
          - template: common/provision.yml
            parameters:
              skipXcode: false
              skipProvisionator: false
              skipAndroidCommonSdks: true
              skipAndroidPlatformApis: true
              skipJdk: true
              skipSimulatorSetup: false
              skipCertificates: true
              skipAndroidEmulatorImages: true
              skipAndroidCreateAvds: true

          # Install .NET and workloads
          - pwsh: ./build.ps1 --target=dotnet --configuration="Release" --verbosity=diagnostic
            displayName: 'Install .NET and workloads'
            retryCountOnTaskFailure: 2
            env:
              DOTNET_TOKEN: $(dotnetbuilds-internal-container-read-token)
              PRIVATE_BUILD: $(PrivateBuild)

          - pwsh: echo "##vso[task.prependpath]$(DotNet.Dir)"
            displayName: 'Add .NET to PATH'

          # Build MSBuild tasks
          - pwsh: ./build.ps1 --target=dotnet-buildtasks --configuration="Release" --verbosity=diagnostic
            displayName: 'Build MSBuild Tasks'
            retryCountOnTaskFailure: 2

          # Boot iOS Simulator
          - script: |
              echo "Available iOS simulators:"
              xcrun simctl list devices available | head -30
              
              # Find and boot a suitable simulator (prefer iOS 26.x, fallback to 18.x)
              UDID=$(xcrun simctl list devices available --json | jq -r '
                .devices | to_entries | 
                map(select(.key | test("iOS.*26|iOS.*18"))) | 
                sort_by(.key) | reverse | 
                .[0].value | 
                map(select(.name | test("iPhone (Xs|14|15)"))) | 
                .[0].udid // empty
              ')
              
              if [ -z "$UDID" ]; then
                echo "No preferred simulator found, using first available iPhone"
                UDID=$(xcrun simctl list devices available --json | jq -r '
                  .devices | to_entries | 
                  map(.value) | flatten | 
                  map(select(.name | test("iPhone"))) | 
                  .[0].udid
                ')
              fi
              
              echo "Booting simulator: $UDID"
              xcrun simctl boot "$UDID" 2>/dev/null || true
              sleep 10
              
              echo "Booted simulators:"
              xcrun simctl list devices booted
              
              echo "##vso[task.setvariable variable=IOS_SIMULATOR_UDID]$UDID"
            displayName: 'Boot iOS Simulator'
            timeoutInMinutes: 5

          # Install Node.js (required for Appium)
          - script: |
              echo "Installing Node.js..."
              brew install node@22 || brew link --overwrite node@22
              node --version
              npm --version
            displayName: 'Install Node.js'

          # Install Appium
          - script: |
              echo "Installing Appium..."
              NPM_BIN=$(npm config get prefix)/bin
              export PATH="$NPM_BIN:$PATH"
              npm install -g appium
              appium driver install xcuitest
              echo "##vso[task.prependpath]$NPM_BIN"
              echo "Appium version: $(appium --version)"
              appium driver list --installed
            displayName: 'Install Appium'

          # Build and Deploy HostApp
          - pwsh: |
              Write-Host "=== Building and Deploying HostApp ==="
              $udid = (xcrun simctl list devices booted --json | ConvertFrom-Json).devices.PSObject.Properties.Value | 
                Where-Object { $_.state -eq "Booted" } | 
                Select-Object -First 1 -ExpandProperty udid
              
              if (-not $udid) {
                Write-Host "##vso[task.logissue type=error]No booted simulator found"
                exit 1
              }
              Write-Host "Using simulator: $udid"
              
              & "./.github/scripts/shared/Build-AndDeploy.ps1" -Platform ios `
                -ProjectPath "src/Controls/tests/TestCases.HostApp/Controls.TestCases.HostApp.csproj" `
                -TargetFramework "net10.0-ios" `
                -DeviceUdid $udid `
                -BundleId "com.microsoft.maui.uitests" `
                -AdditionalBuildArgs @("/p:_RequireCodeSigning=false", "/p:CodesignRequireProvisioningProfile=false") `
                -Verbose
              
              if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
            displayName: 'Build and Deploy HostApp'
            timeoutInMinutes: 30

          # Run UI Tests
          - pwsh: |
              Write-Host "=== Running UI Tests ==="
              & "./.github/scripts/BuildAndRunHostApp.ps1" -Platform ios -Category "Button" -Verbose
              $exitCode = $LASTEXITCODE
              Write-Host "UI Tests completed with exit code: $exitCode"
              exit $exitCode
            displayName: 'Run UI Tests on Simulator'
            timeoutInMinutes: 30

          # Publish test logs
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Test Logs'
            inputs:
              targetPath: 'CustomAgentLogsTmp'
              artifact: 'TestLogs'
            condition: succeededOrFailed()
